name: 'Add Size Label to PR'
author: 'ranemihir/Flowdify'
description: 'A GitHub Action to add relevant size label to PR based on the change in LOC.'
branding:
  icon: 'tag'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub Access Token'
    required: true
  pull-request--size-small:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 50
  pull-request--size-medium:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 200
  pull-request--size-large:
    description: 'Size of the pull request measured by the lines of code changed.'
    required: false
    default: 400

runs:
  using: 'node20'
  main: 'dist/index.js'
